name: Reusable workflow hello

on:
  workflow_call:
    inputs:
          who-to-greet:
            required: true
            type: string
jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print Hello
        run: echo "Hello ${{ inputs.who-to-greet }}"
