name: Build and Publish Docker Image

on:
  workflow_call:
    inputs:
      service-name:
        required: true
        type: string
      docker-login-username:
        required: true
        type: string
      docker-login-password:
          required: true
          type: string
              

jobs:
  build-and-publish-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Authenticate Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ inputs.docker-login-username }}
          password: ${{ inputs.docker-login-password }}

      - name: Build and Publish the Docker Image
        run: |
          docker build -t ghcr.io/abi-interoperability-thesis/{{inputs.service-name}}:latest .
          docker push ghcr.io/abi-interoperability-thesis/{{inputs.service-name}}:latest
